name: Test Action Docker
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - name: Run my own container
        id: my-action
        uses: ./
        with:
          who-to-greet: 'The pips'

      - name: Ouput the answer
        run: echo "The answer is ${{ steps.my-action.outputs.answer }}"

      - name: Test container
        if: ${{ steps.my-action.outputs.answer != 42 }}
        run: |
          echo "::error file=entrypoint.sh,line=4,title=Error in container::The answer is wrong"
          exit 1