name: Show the secret

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  dater:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Add text
        run: |
          echo "This is the secret ${{ secrets.EMAIL }}"
          echo "This is the other secret ${{ secrets.ACTOR }}"
