name: Workflow run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  greeter:
    runs-on: ubuntu-latest
    steps:
      - name: Greeting
        run: echo "Hello stranger"
      - name: Boasting
        run: |
          echo "The contents of the repo ${{ github.repository }} are:"
          tree